'use strict';

var Backbone = require('backbone');

var Collection = Backbone.Collection.extend({
    model:Backbone.Model.extend({})
});

var mockCollection = module.exports = new Collection();

mockCollection.set([
    {
        "title":"App",
        "link":"app"
    },
    {
        "title":"Router",
        "link":"router"
    },
    {
        "title":"Page",
        "link":"page"
    },
    {
        "title":"PageRegion",
        "link":"pageregion"
    },
    {
        "title":"PageController",
        "link":"pagecontroller"
    },
    {
        "title":"Env",
        "link":"env"
    },
    {
        "title":"Device",
        "link":"device"
    },
    {
        "title":"Url",
        "link":"link"
    },
    {
        "title":"UI",
        "link":"ui"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
    {
        "title":"凑数的..",
        "link":"link"
    },
]);
